### ISSUE TITLE
Add support for line charts

### ISSUE THREAD

**Issue by mpellicer** [wwalc/chart#1]
First at all thank you so much for the contribution, worked perfectly for CKEditor 4.3.

Do you think it's interesting to add more charts? Line chart for example, i think the current input is enough to create line charts.

http://www.chartjs.org/docs/#line-chart

Thank you again and regards, Miguel

**Comment by wwalc** [comment]
Thanks Miguel for your feedback. Sure, that should be easily doable. If you have any further suggestions, feel free to post them.

**Comment by wwalc** [comment]
It took a while but it's done. Thanks for your suggestion.
