### ISSUE TITLE
Compatibility Issue

### ISSUE THREAD

**Issue by raj7749** [wwalc/chart#2]
Hi,

Could you let me know the base version of ckeditor.js file on which chart plugin is built. I am facing compatibly issue in version 3.6.6.1 and version 4.3.5

Thanks and regards,
Rajesh

**Comment by raj7749** [comment]
worked in version 4.4.7

**Comment by wwalc** [comment]
It may happen that you were missing some dependencies like the widget plugin or so. Btw. you may want to download the updated version of a plugin ;)
